name: Publish Docker Image
on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md
    - action.yaml
    - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.repository }}/file-changelog-issue-action
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com